### PR TITLE
Tsmedal hpos support

### PR DESCRIPTION
**Pull request by MSmedal**

### CODE REVIEW

**Comment by mayur-vachchewar** [comment]
@MSmedal after installing, I found this error : 
image

**Comment by MSmedal** [comment]
> @MSmedal after installing, I found this error : image

When this error occurred, did you already have WooCommerce installed? [It's a method from WooCommerce](https://developer.woocommerce.com/docs/conditional-tags-in-woocommerce/).

I'm also a little confused as to why you're seeing that error since the method isn't one I introduced with my changes.

**Comment by mayur-vachchewar** [comment]
@MSmedal this scenario can be reproduces if by only installing the plugin, and if not activate the plugin.
As I download and install the plugin from you repo, and before activating the plugin I faced this issue.

Once the plugin is get activated, now that issue does not appear. 
It might be an expected behavior if plugin not activate, but as what I caught I thought to get you noticed on it.

**Comment by MSmedal** [comment]
> @MSmedal this scenario can be reproduces if by only installing the plugin, and if not activate the plugin. As I download and install the plugin from you repo, and before activating the plugin I faced this issue.
> 
> Once the plugin is get activated, now that issue does not appear. It might be an expected behavior if plugin not activate, but as what I caught I thought to get you noticed on it.

OK, so just to be clear this error can be reproduced by installing/activating **our** plugin before installing/activating the main WooCommerce plugin. Can you confirm?

If so then it may make sense to add WooCommerce as a dependency in some way. I'm still a little unsure why this is only becoming an issue now, but it won't be any trouble to account for it regardless.

**Comment by mayur-vachchewar** [comment]
@MSmedal I found this Deprecated warnings, 
image

and also I found this error on checkout page:
image

Please let me know if anything.

**Comment by MSmedal** [comment]
@mayur-vachchewar though we can safely ignore anything in the MasterPass-related classes, I have went ahead and addressed those deprecation warnings.

Regarding the 'no payment methods' error you're seeing, please refer to the note on [our installation page](https://wordpress.org/plugins/woocommerce-securesubmit-gateway/#installation)

**Comment by mayur-vachchewar** [comment]
@MSmedal I have test with the updated code, and able to placed order successfully. Looks perfect.

**Review by mayur-vachchewar — APPROVED** [review]

**Pull request merged**
